---

- name: ensure required modules are installed
  modprobe:
    name: "{{ item }}"
    state: present
  with_items: "{{ crio_kernel_modules }}"

- name: install /etc/sysctl.d/99-kubernetes-cri.conf from template
  template:
    src: "etc/sysctl.d/99-kubernetes-cri.conf"
    dest: "/etc/sysctl.d/99-kubernetes-cri.conf"
  notify: reload sysctl

# FIXME: policy.json maybe solved by installed skopeo?
- name: ensure /etc/containers exists
  file:
    path: "/etc/containers"
    state: "directory"

- name: install /etc/containers/policy.json from template
  template:
    src: "etc/containers/policy.json"
    dest: "/etc/containers/policy.json"

- name: test if running in CI
  set_fact:
    ci: "{{ lookup('env','CI') | bool }}"
  ignore_errors: True

# NOTE: If we are running in travis, we are running docker in docker
# and that causes all kinds of issues...
- name: check if we are running in a CI system
  file:
    dest: "/etc/containers/storage.conf"
    content: |
      [storage]
      driver = "vfs"
  notify: restart crio
  when: >
    ci is defined and
    ci == True
